<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesMatchRecordPlayerProxy extends \Entities\MatchRecordPlayer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setMatchId($matchId)
    {
        $this->__load();
        return parent::setMatchId($matchId);
    }

    public function getMatchId()
    {
        $this->__load();
        return parent::getMatchId();
    }

    public function setInvolvedTeam($involvedTeam)
    {
        $this->__load();
        return parent::setInvolvedTeam($involvedTeam);
    }

    public function getInvolvedTeam()
    {
        $this->__load();
        return parent::getInvolvedTeam();
    }

    public function setUserType($userType)
    {
        $this->__load();
        return parent::setUserType($userType);
    }

    public function getUserType()
    {
        $this->__load();
        return parent::getUserType();
    }

    public function setStadioomId($stadioomId)
    {
        $this->__load();
        return parent::setStadioomId($stadioomId);
    }

    public function getStadioomId()
    {
        $this->__load();
        return parent::getStadioomId();
    }

    public function setOtherId($otherId)
    {
        $this->__load();
        return parent::setOtherId($otherId);
    }

    public function getOtherId()
    {
        $this->__load();
        return parent::getOtherId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'matchId', 'involvedTeam', 'userType', 'stadioomId', 'otherId');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}