<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesUserFbProxy extends \Entities\UserFb implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setFbId($fbId)
    {
        $this->__load();
        return parent::setFbId($fbId);
    }

    public function getFbId()
    {
        $this->__load();
        return parent::getFbId();
    }

    public function setFbAccessToken($fbAccessToken)
    {
        $this->__load();
        return parent::setFbAccessToken($fbAccessToken);
    }

    public function getFbAccessToken()
    {
        $this->__load();
        return parent::getFbAccessToken();
    }

    public function setFbExpires($fbExpires)
    {
        $this->__load();
        return parent::setFbExpires($fbExpires);
    }

    public function getFbExpires()
    {
        $this->__load();
        return parent::getFbExpires();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setLocale($locale)
    {
        $this->__load();
        return parent::setLocale($locale);
    }

    public function getLocale()
    {
        $this->__load();
        return parent::getLocale();
    }

    public function setTimezone($timezone)
    {
        $this->__load();
        return parent::setTimezone($timezone);
    }

    public function getTimezone()
    {
        $this->__load();
        return parent::getTimezone();
    }

    public function setBirthday($birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setHometown($hometown)
    {
        $this->__load();
        return parent::setHometown($hometown);
    }

    public function getHometown()
    {
        $this->__load();
        return parent::getHometown();
    }

    public function setLocation($location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function setFavoriteAthletes($favoriteAthletes)
    {
        $this->__load();
        return parent::setFavoriteAthletes($favoriteAthletes);
    }

    public function getFavoriteAthletes()
    {
        $this->__load();
        return parent::getFavoriteAthletes();
    }

    public function setFavoriteTeams($favoriteTeams)
    {
        $this->__load();
        return parent::setFavoriteTeams($favoriteTeams);
    }

    public function getFavoriteTeams()
    {
        $this->__load();
        return parent::getFavoriteTeams();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addLikes(\Entities\LikesFb $likes)
    {
        $this->__load();
        return parent::addLikes($likes);
    }

    public function getLikes()
    {
        $this->__load();
        return parent::getLikes();
    }

    public function addActivities(\Entities\ActivitiesFb $activities)
    {
        $this->__load();
        return parent::addActivities($activities);
    }

    public function getActivities()
    {
        $this->__load();
        return parent::getActivities();
    }

    public function addInterests(\Entities\InterestsFb $interests)
    {
        $this->__load();
        return parent::addInterests($interests);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'fbId', 'fbAccessToken', 'fbExpires', 'name', 'gender', 'locale', 'timezone', 'birthday', 'hometown', 'location', 'favorite_athletes', 'favorite_teams');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}